source "http://rubygems.org"
gemspec

gem 'bcrypt-ruby', '3.0.1'
gem 'mysql2'
gem 'pry'


# Gems for authenticators
group :ldap do
    gem "net-ldap", "~> 0.1.1"
end

group :active_resource do
  gem "activeresource", ">= 2.3.12", "< 4.0"
end
