source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'rails-erd'
# gem 'amalgalite', '1.1.2'
gem 'amalgalite'
gem 'postgres-pr'
gem 'mysql2'
gem "therubyracer"
gem "less-rails" #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
gem 'twitter-bootstrap-rails', :git => 'git://github.com/seyhunak/twitter-bootstrap-rails.git'
gem 'bootstrap-glyphicons'
gem 'ruby-mysql'
# gem 'ruby-mysql-ext'
gem 'mongo', '1.6.4'
gem 'rethinkdb', '1.2.6.1'
gem 'cql-rb'
gem 'bson'
gem 'bson_ext'
# gem 'json', '1.8.0'
gem 'json'
gem 'i18n-js'
gem 'gon'
gem 'pry'
gem 'activeresource'
gem 'sidekiq'
gem 'bunny'

gem 'devise'
gem 'devise_cas_authenticatable'
gem 'rubycas-client'
# group :assets do
# gem 'sprockets-rails', github: 'rails/sprockets-rails'
gem 'sass-rails',   github: 'rails/sass-rails'
gem 'coffee-rails', github: 'rails/coffee-rails'
gem 'foreman'
gem 'uglifier'
gem 'underscore-rails'
gem "rails-backbone"
gem 'keymaster-rails'

# end

gem 'jquery-rails'

group :test do
  gem 'minitest'
end
