source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use sqlite3 as the database for Active Record
gem 'mysql2','0.3.11'
gem "rails-erd"
gem 'execjs'
gem "devise"
gem "therubyracer", "~> 0.11.4"
gem 'bcrypt-ruby', '3.0.1'
gem 'pry'
gem 'ruby-hmac'
gem 'net-ssh'
# Bootstrap 3 RC2
gem 'anjlab-bootstrap-rails', :require => 'bootstrap-rails', :github => 'anjlab/bootstrap-rails', :branch => '3.0.0'
gem 'bootstrap-glyphicons'

gem 'redis'
gem 'redis-objects', :require => 'redis/objects'
gem 'resque', :require => 'resque/server'
gem 'resque-scheduler', :require => 'resque_scheduler'
gem 'resque-pool', '0.2.0'
gem 'sidekiq'
gem 'rubycas-client'


gem 'spice-html5-rails', github: 'DxTa/spice-html5-rails'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'
gem "foreman", "~> 0.63.0"

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  # gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
